# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)

1.19.5


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
arr = np.random.randint(1,10,(4,4))

print(arr.itemsize * arr.size)

128


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
print(np.info(np.add))

None


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
print(arr[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
arr = np.array([1,2,0,0,4,0])
print(np.nonzero(arr))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
arr = np.random.randint(1,10,(3,3,3))
print(arr)

[[[2 3 5]
  [6 7 3]
  [2 3 3]]

 [[8 1 6]
  [1 7 6]
  [4 4 9]]

 [[5 8 9]
  [1 6 8]
  [9 1 4]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
arr = np.random.randint(10,100,(10,10))
print(np.min(arr))
print(np.max(arr))

10
99


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
arr = np.random.randint(0,10,(30))
print(np.mean(arr))

4.6


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
arr = np.ones((10,10))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
 z = np.ones((5,5))

 np.pad(z, (1,1) ,  'constant', constant_values= 0 )

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)


nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
np.diag([1,2,3,4],k=0)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
arr = np.zeros((8,8))

print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
arr[1::2,::2]=1
arr[::2,1::2]=1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:

np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
np.tile([[1,0],[0,1]] ,(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
arr = np.random.randint(0,10,(5,5))
amin = np.min(arr)
amax = np.max(arr)

print((arr-amin)/(amax-amin))

[[0.44444444 1.         0.         1.         0.11111111]
 [0.55555556 0.44444444 1.         0.33333333 0.77777778]
 [0.88888889 0.88888889 0.11111111 1.         0.66666667]
 [0.55555556 0.22222222 0.11111111 1.         0.66666667]
 [0.33333333 0.11111111 0.11111111 0.11111111 0.11111111]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
colour = np.dtype([('r',np.ubyte , 1),('g',np.ubyte,1) , ('b',np.ubyte,1),('a',np.ubyte,1)] )

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
arr1 = np.random.randint(0,10,(5,3))
arr2 = np.random.randint(0,10,(3,2))

np.dot(arr1,arr2)

array([[25, 62],
       [15, 65],
       [15, 53],
       [ 0, 71],
       [30, 99]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
arr = np.arange(10)

arr[(3>arr) & (arr<8)]  *= -1
arr

array([ 0, -1, -2,  3,  4,  5,  6,  7,  8,  9])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1)) #numpy is omited for start

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z = np.arange(10)
print(z)
print(z**z) # True because boadcasting applies as a power
print(2 << z >> 2)  #bit shift operators
print(z<-z)  # just a comparision operator 
print(1j*z) # complex numbers
print(z/1/1) #just division operator in broadcasting 
print(z<z>z) # comparison opetators are ok but these are not correctly represent


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))  #division is not correct
print(np.array([np.nan]).astype(int).astype(float))

nan
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
arr = np.random.uniform(-10,10,10)
print(arr)
# np.abs turn the values into absolute values 
#ceil tourn the value into roundup eg:- 0.5 to 1
#copysign assign sign from one array to another array
print(np.copysign(np.ceil(np.abs(arr)), arr))

[-9.19346588 -5.92113248  6.57724272 -9.43122502 -0.69327437 -2.01050293
 -6.29756884 -0.11833233  7.15188159 -4.15445844]
[-10.  -6.   7. -10.  -1.  -3.  -7.  -1.   8.  -5.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
arr = np.random.randint(0,10,100)
arr1 = np.random.randint(0,10,100)
print(arr,arr1)
np.intersect1d(arr,arr1)

[4 6 6 6 7 4 0 8 7 7 2 4 5 1 8 1 7 2 7 7 3 5 1 6 3 2 6 9 7 4 1 2 5 4 6 2 9
 4 0 4 9 9 4 8 5 7 3 3 3 9 3 2 0 1 7 6 9 2 3 4 9 5 8 0 8 5 5 7 8 4 8 5 1 2
 6 5 8 6 9 0 1 5 4 3 9 8 5 3 8 6 8 9 8 9 5 0 8 0 8 9] [1 3 8 7 0 8 9 0 4 2 2 3 0 3 8 0 3 8 2 3 2 0 3 4 9 2 2 4 7 2 1 9 8 4 9 5 3
 9 4 6 5 2 1 7 2 6 7 7 0 9 2 0 2 5 5 0 9 6 6 0 1 6 6 7 4 7 8 8 3 5 3 6 9 8
 2 6 8 9 5 5 6 5 7 6 4 6 5 2 9 6 9 2 1 4 8 8 7 2 2 1]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
np.seterr(all='ignore')
np.ones(1)/0

_ = np.seterr()
np.ones(1)/0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1)) # returns the nan value
print(np.emath.sqrt(-1)) # returns the complex number
#so the answer is false

nan
1j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
print(np.datetime64('today','D')-1)
print(np.datetime64('today'))
print(np.datetime64('today','D')+1)
print(np.timedelta64(1,'D'))

2021-06-17
2021-06-18
2021-06-19
1 days


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
np.arange('2016-07','2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
a = np.ones(3)*1
b = np.ones(3)*2

#out is the argument that stores the ouput in that variable

np.add(a,b,out=b)
np.negative(a,out=a)

np.divide(a,2, out =a)
np.multiply(a,b , out=b)
b

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
z = np.random.uniform(0,10,10)
print(z - z%1)

[6. 9. 0. 1. 2. 5. 5. 4. 9. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
np.tile(np.arange(0,5),(5,1))


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
iter = [x for x in range(10)]
np.fromiter(iter,int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
np.linspace(0,1,10,endpoint=True)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
np.sort(np.random.randint(0,10,10))

array([0, 2, 3, 4, 5, 5, 7, 8, 8, 9])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
np.add.reduce(np.arange(4))

6

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
arr = np.arange(10)
arr1 = np.array([0,1,2,3,4,5,6,7,8,9.1])
print(arr,arr1)
print(np.array_equal(arr,arr1))
print(np.allclose(arr,arr1))


[0 1 2 3 4 5 6 7 8 9] [0.  1.  2.  3.  4.  5.  6.  7.  8.  9.1]
False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
arr= np.arange(10)
arr.flags.writeable = False
arr[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
import numpy as np
arr = np.random.randint(1,10,(10,2))
print(arr)
arr[:,0]

[[6 2]
 [4 6]
 [2 9]
 [1 9]
 [6 7]
 [5 4]
 [1 2]
 [3 5]
 [5 1]
 [7 9]]


array([6, 4, 2, 1, 6, 5, 1, 3, 5, 7])

In [ ]:
arr = np.random.randint(1,10,(10,2))
r = np.sqrt(np.square(arr[:,0])+np.square(arr[:,1]))
teta = np.arctan(np.divide(arr[:,1],arr[:,0]))
ab = np.stack((r,teta),axis=1)
print(ab)

[[ 4.12310563  1.32581766]
 [ 7.61577311  0.40489179]
 [ 2.23606798  1.10714872]
 [ 8.06225775  0.12435499]
 [10.63014581  0.85196633]
 [ 5.09901951  0.19739556]
 [ 5.65685425  0.78539816]
 [ 7.21110255  0.5880026 ]
 [ 6.40312424  0.67474094]
 [ 4.47213595  1.10714872]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
arr = np.random.randint(1,10,10)
arr[np.argmax(arr)]=0
arr

array([4, 8, 2, 5, 2, 0, 6, 5, 5, 9])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])

Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),

np.linspace(0,1,5))

print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X = np.arange(8)

Y = X + 0.5

C = 1.0 / np.subtract.outer(X, Y)

print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:

  print(np.iinfo(dtype).min)

  print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:

  print(np.finfo(dtype).min)

  print(np.finfo(dtype).max)

  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=np.nan)
print(np.zeros((16,16)))

ValueError: ignored

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
arr = np.arange(100)
v  = np.random.uniform(0,100)
index = np.abs(arr-v).argmin()
print(arr[index])

73


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),

('y', float, 1)]),

('color', [ ('r', float, 1),

('g', float, 1),

('b', float, 1)])])

print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  if __name__ == '__main__':


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
"""arr = np.random.random((100,2))
x ,y = np.atleast_2d(arr[:,0],arr[:,1])
print(np.sqrt( (x-x.T)**2 + (y-y.T)**2))"""


'arr = np.random.random((100,2))\nx ,y = np.atleast_2d(arr[:,0],arr[:,1])\nprint(np.sqrt( (x-x.T)**2 + (y-y.T)**2))'

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
n =np.arange(100,dtype=np.int32)
n=n.astype(np.float32)
n.dtype

dtype('float32')

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

fi = StringIO("""1, 2, 3, 4, 5\n
6,  ,  , 7, 8\n
 ,  , 9,10,11\n""")
print(np.genfromtxt(fi, delimiter=',',dtype=np.int))


[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):

  print(index, value)

for index in np.ndindex(Z.shape):

  print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))

D = np.sqrt(X*X+Y*Y)

sigma, mu = 1.0, 0.0

G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )

print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
np.random.choice(range(10*10),2)

array([98, 49])

In [ ]:
# array , position , values
n = 10
p =2
arr = np.zeros((n,n))
np.put(arr,  np.random.choice(range(n*n)   ,p ),1)
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
arr = np.random.rand(5,10)
arr = arr - arr.mean(axis=1)
arr

In [ ]:
X = np.random.rand(5, 10)

# Recent versions of numpy

Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy

Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
#argsort returns the sort of the indices 
arr = np.random.randint(0,3,(3,3))
print(arr)
print(arr[arr[:,2].argsort()])

[[0 1 1]
 [2 2 2]
 [0 0 1]]
[[0 1 1]
 [0 0 1]
 [2 2 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
arr = np.random.randint(0,3,(3,3))
print(arr)
print(~arr.any())

[[1 1 0]
 [2 0 1]
 [1 2 1]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
Z = np.random.uniform(0,1,10)

z = 0.5

m = Z.flat[np.abs(Z - z).argmin()]

print(m)

0.5084065794914956


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)

B = np.arange(3).reshape(1,3)

it = np.nditer([A,B,None])

for x,y,z in it: z[...] = x + y

print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
Z = np.ones(10)

I = np.random.randint(0,len(Z),20)

Z += np.bincount(I, minlength=len(Z))

print(Z)

[1. 7. 3. 2. 4. 5. 3. 2. 1. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]

I = [1,3,9,3,4,1]

F = np.bincount(I,X)

print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w , h = 16, 16
l = np.random.randint(0,2 , (h,w,3)).astype(np.ubyte)

F = l[...,0]*256*256 + l[...,1]*256 +l[...,2]

n = len(np.unique(F))

print(np.unique(l))


[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)

print(sum)

3


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)

S = np.random.randint(0,10,100)

D_sums = np.bincount(S, weights=D)

D_counts = np.bincount(S)

D_means = D_sums / D_counts

print(D_means)

[0.39089928 0.42113136 0.48805326 0.55272218 0.64332726 0.51066752
 0.3935582  0.62012679 0.57089299 0.21844855]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
arr = np.random.uniform(0,1,(5,5))
arr1 = np.random.uniform(0,1,(5,5))
np.diag(np.dot(arr,arr1))

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
arr = np.array([1,2,3,4,5])
no = np.zeros(17)
no[::4] = arr #boardcasting applied here
no

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
arr = np.random.randint(1,10,(5,5,3))
arr1 = np.random.randint(1,10,(5,5))

arr1[:,:,None].shape # (5,5,1)
arr*arr1[:,:,None]

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
arr = np.random.randint(1,10,(5,5,3))
print(arr)

arr[[0,1]] = arr[[0,1]]
print(arr)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))

F = np.roll(faces.repeat(2,axis=1),-1,axis=1)

F = F.reshape(len(F)*3,2)

F = np.sort(F,axis=1)

G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )

G = np.unique(G)

print(G)

[( 3, 64) ( 3, 74) (12, 24) (12, 25) (16, 61) (16, 62) (20, 49) (20, 52)
 (21, 68) (21, 97) (22, 34) (22, 42) (24, 25) (34, 42) (37, 40) (40, 40)
 (40, 48) (40, 68) (47, 59) (47, 91) (48, 68) (49, 52) (51, 59) (51, 91)
 (59, 91) (61, 62) (64, 74) (68, 97)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
arr = np.bincount([1,1,2,3,4,4,6])
a = np.repeat(np.arange(len(arr)),arr)
a

array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n=3) :

  ret = np.cumsum(a, dtype=float)

  ret[n:] = ret[n:] - ret[:-n]

  return ret[n - 1:] / n

Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks
def rolling(arr, window):
  shape = ( arr.size - window+1 , window)
  strides  = (arr.itemsize , arr.itemsize)
  return stride_tricks.as_strided(arr, shape=shape, strides=strides)

a = rolling(np.arange(10) , 3)
print(a)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
arr = np.random.randint(0,2,(100))

np.logical_not(arr , out = arr)

arr = np.random.uniform(-1.0,1.0 , 100)
print(arr)
np.negative(arr, out= arr)

[-4.39088547e-01 -1.69844422e-01  5.18471285e-02 -1.81213381e-02
 -2.93589668e-01  4.02060691e-01  7.04978780e-01  3.09154586e-01
 -6.72441827e-01  3.75664317e-01 -2.07236017e-01 -9.78163251e-01
  6.82077132e-01 -8.94854934e-01 -3.11743699e-01 -9.40668755e-01
 -9.52781502e-01 -9.41622544e-01 -4.13065445e-01  1.17590261e-01
 -7.78610872e-01 -9.96032735e-01  2.89919232e-01 -6.07194359e-01
  7.23840510e-01 -8.78212038e-01 -2.98255976e-01 -1.56077868e-01
  4.17092998e-01  7.04046426e-01 -8.04677725e-01 -7.35152985e-01
  8.09545084e-01 -2.26218223e-01  6.40719197e-01 -3.44353373e-01
 -2.93651350e-01 -1.31017275e-01  7.77056870e-01 -3.57916347e-01
  8.01642279e-01 -3.98846992e-01  2.32731831e-01  7.04827988e-01
  9.56639250e-01 -7.37457592e-01 -9.37198204e-01  4.07997752e-01
  3.90654161e-01 -7.78092173e-01 -9.04890386e-01  4.98022845e-01
  8.22623217e-01  5.24715702e-01 -5.74367224e-01  5.11271829e-01
 -4.73425243e-01 -5.19325088e-01  4.60272992e-01  9.15424412e-01
 -4.41867991e-01  2.35655

array([ 4.39088547e-01,  1.69844422e-01, -5.18471285e-02,  1.81213381e-02,
        2.93589668e-01, -4.02060691e-01, -7.04978780e-01, -3.09154586e-01,
        6.72441827e-01, -3.75664317e-01,  2.07236017e-01,  9.78163251e-01,
       -6.82077132e-01,  8.94854934e-01,  3.11743699e-01,  9.40668755e-01,
        9.52781502e-01,  9.41622544e-01,  4.13065445e-01, -1.17590261e-01,
        7.78610872e-01,  9.96032735e-01, -2.89919232e-01,  6.07194359e-01,
       -7.23840510e-01,  8.78212038e-01,  2.98255976e-01,  1.56077868e-01,
       -4.17092998e-01, -7.04046426e-01,  8.04677725e-01,  7.35152985e-01,
       -8.09545084e-01,  2.26218223e-01, -6.40719197e-01,  3.44353373e-01,
        2.93651350e-01,  1.31017275e-01, -7.77056870e-01,  3.57916347e-01,
       -8.01642279e-01,  3.98846992e-01, -2.32731831e-01, -7.04827988e-01,
       -9.56639250e-01,  7.37457592e-01,  9.37198204e-01, -4.07997752e-01,
       -3.90654161e-01,  7.78092173e-01,  9.04890386e-01, -4.98022845e-01,
       -8.22623217e-01, -

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):

  T = P1 - P0

  L = (T**2).sum(axis=1)

  U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L

  U = U.reshape(len(U),1)

  D = P0 + U*T - p

  return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))

P1 = np.random.uniform(-10,10,(10,2))

p = np.random.uniform(-10,10,( 1,2))

print(distance(P0, P1, p))

[ 7.34271177  3.26062122  1.23907934 11.93457295  0.01267717  1.46081682
 12.3037781   3.71033542  2.97183116  8.52640253]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))

P1 = np.random.uniform(-10,10,(10,2))

p = np.random.uniform(-10, 10, (10,2))

print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 5.67484887  7.55511822 10.98250252 14.61551744  8.29822757  0.16508453
   5.12037523 12.95269981  0.44416846  1.97419536]
 [10.36017904 13.80972191  5.15989968  1.72781273  2.81571157  1.11276613
   7.58018234  5.0470895   7.95157554  6.63864331]
 [11.70076453  1.38306655  4.83774186 18.46738249  7.39860167 12.70281958
   6.73169225  3.9349162   8.01414008  8.49118365]
 [ 0.51633082  0.83584729 10.12504512  8.56676988  7.57635256  1.73282024
   7.46207203  6.88263265  4.6313787   5.13216712]
 [ 2.18889969  0.50525137 12.00241617  7.53185321  9.4509801   3.45866159
   9.14409411  8.4106765   6.06409687  6.71806719]
 [11.41233074  8.61069783  0.36069991  9.15697537  2.07500737  5.2694051
   0.99918045  5.01273257  0.73769009  0.26318479]
 [ 1.09821289  8.91518087 13.50572931  0.16231474 11.09351197  7.66849317
  13.76497118  3.97870716 12.30834067 12.07509208]
 [ 0.4161985   0.91826976  9.01014162  9.27151991  6.46122141  0.67077233
   6.42018864  6.04944502  3.71361025  4.13669013]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))

shape = (5,5)

fill = 0

position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill

P = np.array(list(position)).astype(int)

Rs = np.array(list(R.shape)).astype(int)

Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)

R_stop = np.array(list(shape)).astype(int)

Z_start = (P-Rs//2)

Z_stop = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()

Z_start = (np.maximum(Z_start,0)).tolist()

R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()

Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]

z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]

R[r] = Z[z]

print(Z)

print(R)

[[8 6 2 6 3 5 6 5 3 7]
 [0 8 6 1 0 0 2 5 0 7]
 [6 5 8 1 1 4 5 7 3 2]
 [4 2 6 1 9 7 4 0 4 4]
 [2 6 4 5 8 9 0 4 4 6]
 [2 2 0 5 3 0 7 0 9 0]
 [0 8 1 1 0 8 9 3 2 0]
 [9 1 8 9 8 3 7 8 9 0]
 [1 4 7 1 0 4 6 4 7 5]
 [2 7 3 6 4 8 1 7 1 6]]
[[0 0 0 0 0]
 [0 8 6 2 6]
 [0 0 8 6 1]
 [0 6 5 8 1]
 [0 4 2 6 1]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:37: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
arr = np.arange(1,15, dtype=np.uint32)
print(stride_tricks.as_strided(arr, (11,4),(4,4)))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z = np.random.uniform(0,1,(10,10))

U, S, V = np.linalg.svd(Z) # Singular Value Decomposition

rank = np.sum(S > 1e-10)

print(rank)



10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
arr = np.random.randint(0,10,100)
print(arr)
print(np.bincount(arr).argmax())

[8 7 6 5 6 9 5 2 7 9 4 4 0 7 6 6 5 4 0 3 2 7 8 5 6 6 2 1 1 9 7 1 3 4 5 3 3
 5 3 7 6 8 5 4 2 9 8 9 3 7 6 3 5 7 7 5 5 6 1 2 3 2 4 3 4 4 8 8 3 0 8 0 5 9
 1 3 5 6 4 2 7 4 2 7 7 2 1 2 1 5 6 5 3 2 9 7 8 7 1 3]
5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.randint(0,5,(10,10))


n = 3

i = 1 + (Z.shape[0]-3)

j = 1 + (Z.shape[1]-3)

C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)

print(C.shape)

(8, 8, 3, 3)


In [ ]:
Z

array([[0, 2, 4, 3, 0, 0, 0, 2, 0, 1],
       [0, 2, 1, 4, 4, 1, 0, 1, 3, 0],
       [0, 2, 2, 1, 4, 1, 0, 3, 1, 4],
       [4, 4, 0, 1, 1, 4, 3, 2, 4, 1],
       [2, 4, 3, 3, 3, 0, 3, 1, 4, 4],
       [1, 1, 0, 0, 0, 3, 1, 1, 0, 3],
       [0, 1, 0, 1, 4, 3, 4, 1, 0, 4],
       [1, 0, 1, 1, 2, 1, 3, 2, 1, 2],
       [2, 4, 0, 2, 3, 1, 0, 3, 0, 0],
       [2, 1, 0, 2, 1, 4, 0, 2, 4, 4]])

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):

  def __setitem__(self, index, value):

    i,j = index

    super(Symetric, self).__setitem__((i,j), value)

    super(Symetric, self).__setitem__((j,i), value)

  def symetric(Z):

    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

    S = symetric(np.random.randint(0,10,(5,5)))

    S[2,3] = 42

print(S)

[5.09206531 1.63700455 1.26292479 1.11962664 0.88278027 0.75261296
 0.50821838 0.3815717  0.15562491 0.09800113]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20

M = np.ones((p,n,n))

V = np.ones((p,n,1))

S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])

print(S)

# It works, because:

# M is (p,n,n)

# V is (p,n,1)

# Thus, summing over the paired axes 0 and 0 (of M and V independently),

# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z = np.ones((16,16))

k = 4

S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),

np.arange(0, Z.shape[1], k), axis=1)

print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):

  # Count neighbours

  N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +

  Z[1:-1,0:-2] + Z[1:-1,2:] +

  Z[2: ,0:-2] + Z[2: ,1:-1] + Z[2: ,2:])

  # Apply rules

  birth = (N==3) & (Z[1:-1,1:-1]==0)

  survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)

  Z[...] = 0

  Z[1:-1,1:-1][birth | survive] = 1

  return Z

Z = np.random.randint(0,2,(50,50))

for i in range(100): Z = iterate(Z)

  print(Z)

IndentationError: ignored

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [13]:
Z = np.arange(10000)

np.random.shuffle(Z)

n = 5



print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [11]:
def cartesian(arrays):

  arrays = [np.asarray(a) for a in arrays]

  shape = (len(x) for x in arrays)

  ix = np.indices(shape, dtype=int)

  ix = ix.reshape(len(arrays), -1).T

  for n, arr in enumerate(arrays):

    ix[:, n] = arrays[n][ix[:, n]]

  return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [9]:
Z = np.array([("Hello", 2.5, 3),

("World", 3.6, 2)])

R = np.core.records.fromarrays(Z.T,

names='col1, col2, col3',

formats = 'S8, f8, i8')

print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(1,100)

%timeit np.power(x,3)

%timeit x * x * x

The slowest run took 7.44 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 8.91 µs per loop
The slowest run took 12.56 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.25 µs per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [8]:
A = np.random.randint(0,5,(8,3))

B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)

rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]

print(rows)

[0 1 2 3 4 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))

E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)

U = Z[~E]

print(Z)

print(U)

[[1 1 2]
 [4 4 1]
 [4 3 1]
 [1 4 3]
 [0 1 3]
 [2 0 0]
 [0 1 2]
 [2 2 0]
 [2 0 1]
 [1 3 4]]
[[1 1 2]
 [4 4 1]
 [4 3 1]
 [1 4 3]
 [0 1 3]
 [2 0 0]
 [0 1 2]
 [2 2 0]
 [2 0 1]
 [1 3 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
print( (2**np.arange(8)))
print(3 & 1 )
print(3 & 2)
print(3 & 4)
print(3 & 8)


[  1   2   4   8  16  32  64 128]
1
2
0
0


In [ ]:

print(((I.reshape(-1,1) & (2**np.arange(8)))))

[[  0   0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0]
 [  0   2   0   0   0   0   0   0]
 [  1   2   0   0   0   0   0   0]
 [  1   2   4   8   0   0   0   0]
 [  0   0   0   0  16   0   0   0]
 [  0   0   0   0   0  32   0   0]
 [  0   0   0   0   0   0  64   0]
 [  0   0   0   0   0   0   0 128]
 [  1   2   0   8   0   0   0   0]]


In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128,11])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)

print(B[:,::-1])


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [7]:
Z = np.random.randint(0,2,(6,3))

T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))

_, idx = np.unique(T, return_index=True)

uZ = Z[idx]

print(uZ)

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [6]:
A = np.random.uniform(0,1,10)

B = np.random.uniform(0,1,10)

np.einsum('i->', A) # np.sum(A)

np.einsum('i,i->i', A, B) # A * B

np.einsum('i,i', A, B) # np.inner(A, B)

np.einsum('i,j', A, B) # np.outer(A, B)

array([[0.51334686, 0.62413318, 0.3999606 , 0.14083924, 0.61310109,
        0.38141588, 0.64612469, 0.0638608 , 0.11867049, 0.30700973],
       [0.61257076, 0.74477077, 0.47726827, 0.1680618 , 0.73160631,
        0.45513908, 0.77101299, 0.07620434, 0.1416081 , 0.36635109],
       [0.21915752, 0.2664543 , 0.17075077, 0.06012694, 0.26174449,
        0.16283368, 0.2758429 , 0.02726339, 0.05066269, 0.13106828],
       [0.06767684, 0.0822823 , 0.05272861, 0.01856747, 0.08082789,
        0.05028378, 0.08518154, 0.00841906, 0.01564487, 0.04047448],
       [0.31691747, 0.385312  , 0.24691784, 0.08694787, 0.37850128,
        0.23546916, 0.39888858, 0.03942481, 0.07326187, 0.18953412],
       [0.47958511, 0.58308524, 0.37365602, 0.13157653, 0.5727787 ,
        0.35633095, 0.60363042, 0.05966081, 0.11086578, 0.28681834],
       [0.62353804, 0.75810492, 0.48581313, 0.17107073, 0.74470476,
        0.46328775, 0.78481697, 0.07756868, 0.14414341, 0.37291013],
       [0.755147  , 0.91811665, 0.5883527

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [5]:
phi = np.arange(0, 10*np.pi, 0.1)

a = 1

x = a*phi*np.cos(phi)

y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5

r = np.zeros_like(x)

r[1:] = np.cumsum(dr)

r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x) 

y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [4]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],

[2.0, 0.0, 1.0, 1.0],

[1.5, 2.5, 1.0, 0.0]])

n = 4

M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)

M &= (X.sum(axis=-1) == n)

print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [3]:
X = np.random.randn(100) 
N = 1000 

idx = np.random.randint(0, X.size, (N, X.size))

means = X[idx].mean(axis=1)

confint = np.percentile(means, [2.5, 97.5])

print(confint)

[-0.25531624  0.13614449]
